services:
  - type: web
    name: fastapi-service
    plan: free
    buildCommand: "pip install -r requirements.txt && cd front && npm install && npm run build"
    runtime: python
    startCommand: "./start.sh"