export {default as Admin} from './Admin'
export {default as Home} from './Home'
export {default as Login} from './Login'
export {default as Main} from './Main'
export {default as Result} from './Result'
export {default as SessionExpired} from './SessionExpired'
